## **Load Homography matrix (from txt) -> Warp/Crop Images**

Given a homography matrix, loaded from a txt file, or manually inputed, numpy array (3,3) and visible images warps the images and saves the outputs in the "aligned" output folder.

In [4]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
import os
from glob import glob

In [ ]:
#Path handler

matrix_path = "homography_matrix.txt" # to save the homography matrix (if good)

visible_folder = "visible" # for the visible images, to warp/transform
output_folder = "aligned" # for the aligned images, to save the warped images

In [5]:
def load_homography_matrix(filename):
    """
    Loads a 3x3 homography matrix from a .txt file.

    Parameters:
        filename (str): Path to the text file containing the matrix.

    Returns:
        np.ndarray: 3x3 Homography matrix.
    """
    H = np.loadtxt(filename, delimiter=',')
    if H.shape != (3, 3):
        raise ValueError(f"Invalid matrix shape {H.shape}. Expected 3x3.")
    print(f"Homography matrix loaded from {filename}")
    return H

In [6]:
def warp_images_from_folder(visible_folder, H, target_shape, output_dir, extensions=[".jpg", ".png", ".jpeg"]):
    """
    Applies a homography matrix to all images in a folder.

    Parameters:
        visible_folder (str): Path to the folder with visible images.
        H (np.ndarray): 3x3 Homography matrix.
        target_shape (tuple): Shape (height, width) to warp images to (from the thermal image).
        output_dir (str): Directory to save warped images.
        extensions (list): List of valid image file extensions.

    Returns:
        None
    """
    os.makedirs(output_dir, exist_ok=True)

    # Get all image files in the folder
    image_paths = []
    for ext in extensions:
        image_paths.extend(glob(os.path.join(visible_folder, f"*{ext}")))

    if not image_paths:
        print("No images found in the folder.")
        return

    for image_path in image_paths:
        img = cv2.imread(image_path)
        if img is None:
            print(f"Warning: Could not read {image_path}")
            continue

        warped_img = cv2.warpPerspective(img, H, (target_shape[1], target_shape[0]))
        filename = os.path.basename(image_path)
        save_path = os.path.join(output_dir, f"aligned_{filename}")
        cv2.imwrite(save_path, warped_img)
        print(f"Saved aligned image to {save_path}")


### **MAIN**

In [ ]:
loaded_H = load_homography_matrix(matrix_path)
print("Loaded Homography Matrix:\n", loaded_H)

Homography matrix loaded from homography_matrix.txt
Loaded Homography Matrix:
 [[ 2.13743710e-01  3.40875000e-03 -6.18438110e+01]
 [-1.75101800e-02  2.71633040e-01 -8.90912446e+01]
 [-9.51600000e-05  3.60600000e-05  1.00000000e+00]]


In [9]:
#target_shape = thermal_img.shape[:2]  # (height, width)
target_shape = (640, 480)

In [10]:
warp_images_from_folder(visible_folder, loaded_H, (640, 480), output_folder)

Saved aligned image to aligned/aligned_HM20240814214018_VIS.jpeg
Saved aligned image to aligned/aligned_HM20240814213403_VIS.jpeg
Saved aligned image to aligned/aligned_HM20240814213710_VIS.jpeg
Saved aligned image to aligned/aligned_HM20240814213507_VIS.jpeg
Saved aligned image to aligned/aligned_HM20240814213609_VIS.jpeg
Saved aligned image to aligned/aligned_HM20240814213916_VIS.jpeg
Saved aligned image to aligned/aligned_HM20240814213814_VIS.jpeg
Saved aligned image to aligned/aligned_HM20240814214120_VIS.jpeg
